environment:

  projectPath: /Volumes/data/temp/flutter_two_demo

  flutterSdkPath: /Volumes/data/flutter_sdk/flutter_change_sdk

  # Compile cache path
  buildCachePath: /Volumes/data/dart_compile_cache

  # FTP
  ftpConfig: 192.168.80.144|ftpuser|ftpuser